# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import enum
import typing

from nautilus_trader import model

__all__ = [
    "ONDO",
    "ONDO_CLIENT_ID",
    "ONDO_VENUE",
    "OndoDataClientConfig",
    "OndoDataClientFactory",
    "OndoEnvironment",
    "OndoExecutionClientConfig",
    "OndoExecutionClientFactory",
]

ONDO: str
ONDO_CLIENT_ID: model.ClientId
ONDO_VENUE: model.Venue

@typing.final
class OndoDataClientConfig:
    @property
    def environment(self) -> OndoEnvironment: ...
    @property
    def load_ids(self) -> list[model.InstrumentId]: ...
    @property
    def base_url_http(self) -> str | None: ...
    @property
    def base_url_ws(self) -> str | None: ...
    @property
    def http_timeout_secs(self) -> int: ...
    @property
    def ws_heartbeat_secs(self) -> int: ...
    @property
    def book_limit(self) -> int: ...
    @property
    def raw_md_path(self) -> str | None: ...
    @property
    def raw_md_run_id(self) -> str | None: ...
    def __init__(
        self,
        environment: OndoEnvironment | None = None,
        load_ids: typing.Sequence[model.InstrumentId] | None = None,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        http_timeout_secs: int | None = None,
        ws_heartbeat_secs: int | None = None,
        book_limit: int | None = None,
        raw_md_path: str | None = None,
        raw_md_run_id: str | None = None,
    ) -> None: ...

@typing.final
class OndoDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class OndoExecutionClientConfig:
    @property
    def environment(self) -> OndoEnvironment: ...
    @property
    def account_id(self) -> model.AccountId | None: ...
    @property
    def base_url_http(self) -> str | None: ...
    @property
    def base_url_ws(self) -> str | None: ...
    @property
    def account_read_only(self) -> bool: ...
    @property
    def http_timeout_secs(self) -> int: ...
    @property
    def dms_timeout_secs(self) -> int: ...
    @property
    def dms_max_failed_renewals(self) -> int: ...
    @property
    def reconcile_interval_secs(self) -> int: ...
    @property
    def journal_path(self) -> str | None: ...
    @property
    def allow_production_orders(self) -> bool: ...
    def __init__(
        self,
        environment: OndoEnvironment | None = None,
        account_id: model.AccountId | None = None,
        api_key: str | None = None,
        api_secret: str | None = None,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        account_read_only: bool | None = None,
        http_timeout_secs: int | None = None,
        dms_timeout_secs: int | None = None,
        dms_max_failed_renewals: int | None = None,
        reconcile_interval_secs: int | None = None,
        journal_path: str | None = None,
        allow_production_orders: bool | None = None,
    ) -> None: ...

@typing.final
class OndoExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class OndoHttpClient:
    def __init__(self, environment: OndoEnvironment, timeout_secs: int = 15) -> None: ...
    def get_status(self) -> dict[str, typing.Any]: ...
    def get_markets(self) -> dict[str, typing.Any]: ...
    def get_contracts(self) -> list[dict[str, typing.Any]]: ...
    def load_instrument_definitions(self, load_ids: typing.Sequence[str]) -> list[typing.Any]: ...

@typing.final
class OndoEnvironment(enum.Enum):
    PRODUCTION = ...
    SANDBOX = ...
