# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import enum
import typing

from nautilus_trader import model
from nautilus_trader.adapters import binance

__all__ = [
    "ASTER",
    "ASTER_CLIENT_ID",
    "ASTER_VENUE",
    "AsterDataClientConfig",
    "AsterDataClientFactory",
    "AsterEnvironment",
    "AsterExecutionClientConfig",
    "AsterExecutionClientFactory",
]

ASTER: str
ASTER_CLIENT_ID: model.ClientId
ASTER_VENUE: model.Venue

@typing.final
class AsterDataClientConfig:
    @property
    def environment(self) -> AsterEnvironment: ...
    @property
    def base_url_http(self) -> str | None: ...
    @property
    def base_url_ws(self) -> str | None: ...
    @property
    def instrument_provider(self) -> binance.BinanceInstrumentProviderConfig: ...
    @property
    def instrument_refresh_interval_secs(self) -> int: ...
    @property
    def instrument_status_poll_secs(self) -> int: ...
    @property
    def proxy_url(self) -> str | None: ...
    @property
    def venue(self) -> model.Venue | None: ...
    def __init__(
        self,
        environment: AsterEnvironment | None = None,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        instrument_provider: binance.BinanceInstrumentProviderConfig | None = None,
        instrument_refresh_interval_secs: int | None = None,
        instrument_status_poll_secs: int | None = None,
        proxy_url: str | None = None,
        venue: model.Venue | None = None,
    ) -> None: ...

@typing.final
class AsterDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class AsterExecutionClientConfig:
    @property
    def account_id(self) -> model.AccountId: ...
    @property
    def environment(self) -> AsterEnvironment: ...
    @property
    def user_address(self) -> str | None: ...
    @property
    def signer_address(self) -> str | None: ...
    @property
    def base_url_http(self) -> str | None: ...
    @property
    def base_url_ws(self) -> str | None: ...
    @property
    def instrument_provider(self) -> binance.BinanceInstrumentProviderConfig: ...
    @property
    def http_timeout_secs(self) -> int | None: ...
    @property
    def ws_heartbeat_secs(self) -> int | None: ...
    @property
    def ws_connect_timeout_secs(self) -> int | None: ...
    @property
    def proxy_url(self) -> str | None: ...
    @property
    def treat_expired_as_canceled(self) -> bool: ...
    @property
    def assume_one_way_mode_when_unconfirmed(self) -> bool: ...
    @property
    def venue(self) -> model.Venue | None: ...
    def __init__(
        self,
        account_id: model.AccountId | None = None,
        environment: AsterEnvironment | None = None,
        user_address: str | None = None,
        signer_address: str | None = None,
        signer_private_key: str | None = None,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        instrument_provider: binance.BinanceInstrumentProviderConfig | None = None,
        http_timeout_secs: int | None = None,
        ws_heartbeat_secs: int | None = None,
        ws_connect_timeout_secs: int | None = None,
        proxy_url: str | None = None,
        treat_expired_as_canceled: bool | None = None,
        assume_one_way_mode_when_unconfirmed: bool | None = None,
        venue: model.Venue | None = None,
    ) -> None: ...
    def has_explicit_credentials(self) -> bool: ...

@typing.final
class AsterExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class AsterEnvironment(enum.Enum):
    MAINNET = ...
    TESTNET = ...
