# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

from nautilus_trader import model

__all__ = [
    "BACKPACK",
    "BACKPACK_CLIENT_ID",
    "BACKPACK_VENUE",
    "BackpackDataClientConfig",
    "BackpackDataClientFactory",
    "BackpackInstrumentEconomics",
    "BackpackPublicReplay",
]

BACKPACK: str
BACKPACK_CLIENT_ID: model.ClientId
BACKPACK_VENUE: model.Venue

@typing.final
class BackpackDataClientConfig:
    @property
    def symbols(self) -> list[str]: ...
    @property
    def economics(self) -> dict[str, BackpackInstrumentEconomics]: ...
    @property
    def base_url_http(self) -> str: ...
    @property
    def base_url_ws(self) -> str: ...
    @property
    def http_timeout_secs(self) -> int: ...
    @property
    def ws_connect_timeout_secs(self) -> int: ...
    @property
    def ws_heartbeat_secs(self) -> int: ...
    @property
    def ws_idle_timeout_secs(self) -> int: ...
    @property
    def reconnect_timeout_secs(self) -> int: ...
    @property
    def shutdown_timeout_secs(self) -> int: ...
    @property
    def quote_stale_after_ms(self) -> int: ...
    @property
    def depth_snapshot_limit(self) -> int: ...
    @property
    def max_buffer_frames(self) -> int: ...
    @property
    def max_levels_per_side(self) -> int: ...
    @property
    def max_ws_message_bytes(self) -> int: ...
    def __new__(
        cls,
        symbols: typing.Sequence[str],
        economics: typing.Mapping[str, BackpackInstrumentEconomics],
        *,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        http_timeout_secs: int | None = None,
        ws_connect_timeout_secs: int | None = None,
        ws_heartbeat_secs: int | None = None,
        ws_idle_timeout_secs: int | None = None,
        reconnect_timeout_secs: int | None = None,
        shutdown_timeout_secs: int | None = None,
        quote_stale_after_ms: int | None = None,
        depth_snapshot_limit: int | None = None,
        max_buffer_frames: int | None = None,
        max_levels_per_side: int | None = None,
        max_ws_message_bytes: int | None = None,
    ) -> BackpackDataClientConfig: ...
    def telemetry_snapshot_json(self) -> str: ...

@typing.final
class BackpackDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
    @property
    def config_type(self) -> str: ...
    def capabilities_json(self) -> str: ...

@typing.final
class BackpackInstrumentEconomics:
    @property
    def margin_init(self) -> str: ...
    @property
    def margin_maint(self) -> str: ...
    @property
    def maker_fee(self) -> str: ...
    @property
    def taker_fee(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def source_reference(self) -> str: ...
    def __new__(
        cls,
        margin_init: str,
        margin_maint: str,
        maker_fee: str,
        taker_fee: str,
        source: str,
        source_reference: str,
    ) -> BackpackInstrumentEconomics: ...

@typing.final
class BackpackPublicReplay:
    @property
    def instrument(self) -> model.CryptoPerpetual: ...
    def __new__(
        cls,
        config: BackpackDataClientConfig,
        market_json: str,
        metadata_received_at_ns: int,
        *,
        generation: int = ...,
    ) -> BackpackPublicReplay: ...
    def apply_record(
        self, record: bytes
    ) -> (
        model.QuoteTick | model.TradeTick | model.MarkPriceUpdate | model.OrderBookDeltas | None
    ): ...
