# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

from nautilus_trader import model

__all__ = [
    "BACKPACK",
    "BACKPACK_CLIENT_ID",
    "BACKPACK_VENUE",
    "BackpackCredential",
    "BackpackDataClientConfig",
    "BackpackDataClientFactory",
    "BackpackExecutionClientConfig",
    "BackpackExecutionClientFactory",
    "BackpackInstrumentEconomics",
    "BackpackLoopbackAccountFacts",
    "BackpackLoopbackControl",
    "BackpackLoopbackExecutionAuthority",
    "BackpackLoopbackExecutionClientConfig",
    "BackpackLoopbackExecutionClientFactory",
    "BackpackLoopbackSession",
    "BackpackPublicReplay",
    "BackpackQuota",
]

BACKPACK: str
BACKPACK_CLIENT_ID: model.ClientId
BACKPACK_VENUE: model.Venue

@typing.final
class BackpackCredential:
    def __new__(
        cls, seed_base64: str, *, base_url_http: str | None = None, base_url_ws: str | None = None
    ) -> BackpackCredential: ...

@typing.final
class BackpackDataClientConfig:
    @property
    def symbols(self) -> list[str]: ...
    @property
    def economics(self) -> dict[str, BackpackInstrumentEconomics]: ...
    @property
    def base_url_http(self) -> str: ...
    @property
    def base_url_ws(self) -> str: ...
    @property
    def http_timeout_secs(self) -> int: ...
    @property
    def ws_connect_timeout_secs(self) -> int: ...
    @property
    def ws_heartbeat_secs(self) -> int: ...
    @property
    def ws_idle_timeout_secs(self) -> int: ...
    @property
    def reconnect_timeout_secs(self) -> int: ...
    @property
    def shutdown_timeout_secs(self) -> int: ...
    @property
    def quote_stale_after_ms(self) -> int: ...
    @property
    def depth_snapshot_limit(self) -> int: ...
    @property
    def max_buffer_frames(self) -> int: ...
    @property
    def max_levels_per_side(self) -> int: ...
    @property
    def max_ws_message_bytes(self) -> int: ...
    def __new__(
        cls,
        symbols: typing.Sequence[str],
        economics: typing.Mapping[str, BackpackInstrumentEconomics],
        *,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        http_timeout_secs: int | None = None,
        ws_connect_timeout_secs: int | None = None,
        ws_heartbeat_secs: int | None = None,
        ws_idle_timeout_secs: int | None = None,
        reconnect_timeout_secs: int | None = None,
        shutdown_timeout_secs: int | None = None,
        quote_stale_after_ms: int | None = None,
        depth_snapshot_limit: int | None = None,
        max_buffer_frames: int | None = None,
        max_levels_per_side: int | None = None,
        max_ws_message_bytes: int | None = None,
    ) -> BackpackDataClientConfig: ...
    def telemetry_snapshot_json(self) -> str: ...

@typing.final
class BackpackDataClientFactory:
    @property
    def quota(self) -> BackpackQuota: ...
    @property
    def config_type(self) -> str: ...
    def __new__(cls, *, quota: BackpackQuota | None = None) -> BackpackDataClientFactory: ...
    def name(self) -> str: ...
    def capabilities_json(self) -> str: ...

@typing.final
class BackpackExecutionClientConfig:
    @property
    def identity_account(self) -> str: ...
    @property
    def subaccount(self) -> str | None: ...
    @property
    def symbols(self) -> list[str]: ...
    @property
    def account_id(self) -> str: ...
    @property
    def identity_directory(self) -> str: ...
    @property
    def quota(self) -> BackpackQuota: ...
    @property
    def base_url_http(self) -> str: ...
    @property
    def base_url_ws(self) -> str: ...
    @property
    def connect_timeout_ms(self) -> int: ...
    @property
    def shutdown_timeout_ms(self) -> int: ...
    @property
    def recovery_interval_ms(self) -> int: ...
    @property
    def recovery_lookback_ms(self) -> int: ...
    @property
    def input_capacity(self) -> int: ...
    @property
    def fill_capacity(self) -> int: ...
    @property
    def page_size(self) -> int: ...
    @property
    def max_pages(self) -> int: ...
    @property
    def max_items(self) -> int: ...
    @property
    def read_timeout_ms(self) -> int: ...
    def __new__(
        cls,
        symbols: typing.Sequence[str],
        credential: BackpackCredential,
        account_id: str,
        identity_account: str,
        identity_directory: str,
        *,
        quota: BackpackQuota,
        subaccount: str | None = None,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        connect_timeout_ms: int = ...,
        shutdown_timeout_ms: int = ...,
        recovery_interval_ms: int = ...,
        recovery_lookback_ms: int = ...,
        input_capacity: int = ...,
        fill_capacity: int = ...,
        page_size: int = ...,
        max_pages: int = ...,
        max_items: int = ...,
        read_timeout_ms: int = ...,
    ) -> BackpackExecutionClientConfig: ...
    def telemetry_snapshot_json(self) -> str: ...

@typing.final
class BackpackExecutionClientFactory:
    @property
    def config_type(self) -> str: ...
    def __new__(cls) -> BackpackExecutionClientFactory: ...
    def name(self) -> str: ...
    def capabilities_json(self) -> str: ...

@typing.final
class BackpackInstrumentEconomics:
    @property
    def margin_init(self) -> str: ...
    @property
    def margin_maint(self) -> str: ...
    @property
    def maker_fee(self) -> str: ...
    @property
    def taker_fee(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def source_reference(self) -> str: ...
    def __new__(
        cls,
        margin_init: str,
        margin_maint: str,
        maker_fee: str,
        taker_fee: str,
        source: str,
        source_reference: str,
    ) -> BackpackInstrumentEconomics: ...

@typing.final
class BackpackLoopbackAccountFacts:
    @property
    def observed_at_ms(self) -> int: ...
    @property
    def available_margin(self) -> str: ...
    @property
    def margin_per_notional(self) -> str: ...
    @property
    def fee_buffer_per_notional(self) -> str: ...
    @property
    def economics_reference(self) -> str: ...
    @property
    def net_positions(self) -> dict[str, str]: ...
    @property
    def auto_borrow(self) -> bool: ...
    @property
    def auto_lend(self) -> bool: ...
    @property
    def auto_repay(self) -> bool: ...
    @property
    def liquidating(self) -> bool: ...
    @property
    def complete(self) -> bool: ...
    def __new__(
        cls,
        *,
        observed_at_ms: int,
        available_margin: str,
        margin_per_notional: str,
        fee_buffer_per_notional: str,
        economics_reference: str,
        net_positions: typing.Mapping[str, str],
        auto_borrow: bool,
        auto_lend: bool,
        auto_repay: bool,
        liquidating: bool,
        complete: bool,
    ) -> BackpackLoopbackAccountFacts: ...

@typing.final
class BackpackLoopbackControl:
    def begin_session(self) -> BackpackLoopbackSession: ...
    def accept_account(
        self, session: BackpackLoopbackSession, facts: BackpackLoopbackAccountFacts
    ) -> None: ...
    def refresh_market(self, session: BackpackLoopbackSession, instrument_id: str) -> None: ...
    def invalidate(self, session: BackpackLoopbackSession) -> None: ...
    def reconcile_terminal_evidence(self, session: BackpackLoopbackSession) -> str: ...
    def persist_economics(self) -> str: ...
    def pending_fills_json(self) -> str: ...
    def telemetry_snapshot_json(self) -> str: ...
    def shutdown_report_json(self) -> str | None: ...

@typing.final
class BackpackLoopbackExecutionAuthority:
    @property
    def expires_at_ms(self) -> int: ...
    @property
    def max_account_age_ms(self) -> int: ...
    @property
    def max_market_age_ms(self) -> int: ...
    @property
    def max_order_notional(self) -> str: ...
    @property
    def max_reserved_notional(self) -> str: ...
    @property
    def max_reserved_margin(self) -> str: ...
    @property
    def max_unsettled_orders(self) -> int: ...
    @property
    def allow_new_risk(self) -> bool: ...
    @property
    def allow_reduction(self) -> bool: ...
    @property
    def allow_owned_cancel(self) -> bool: ...
    def __new__(
        cls,
        *,
        expires_at_ms: int,
        max_account_age_ms: int,
        max_market_age_ms: int,
        max_order_notional: str,
        max_reserved_notional: str,
        max_reserved_margin: str,
        max_unsettled_orders: int,
        allow_new_risk: bool,
        allow_reduction: bool,
        allow_owned_cancel: bool,
    ) -> BackpackLoopbackExecutionAuthority: ...

@typing.final
class BackpackLoopbackExecutionClientConfig:
    @property
    def read_only_config(self) -> BackpackExecutionClientConfig: ...
    @property
    def public_config(self) -> BackpackDataClientConfig: ...
    @property
    def authority(self) -> BackpackLoopbackExecutionAuthority: ...
    @property
    def mutation_budget_ms(self) -> int: ...
    @property
    def receive_window_ms(self) -> int: ...
    @property
    def economic_state_directory(self) -> str | None: ...
    @property
    def control(self) -> BackpackLoopbackControl: ...
    def __new__(
        cls,
        read_only_config: BackpackExecutionClientConfig,
        public_config: BackpackDataClientConfig,
        *,
        authority: BackpackLoopbackExecutionAuthority,
        mutation_budget_ms: int,
        receive_window_ms: int,
        economic_state_directory: str | None = None,
    ) -> BackpackLoopbackExecutionClientConfig: ...

@typing.final
class BackpackLoopbackExecutionClientFactory:
    @property
    def config_type(self) -> str: ...
    def __new__(cls) -> BackpackLoopbackExecutionClientFactory: ...
    def name(self) -> str: ...
    def capabilities_json(self) -> str: ...

@typing.final
class BackpackLoopbackSession:
    @property
    def generation(self) -> int: ...

@typing.final
class BackpackPublicReplay:
    @property
    def instrument(self) -> model.CryptoPerpetual: ...
    def __new__(
        cls,
        config: BackpackDataClientConfig,
        market_json: str,
        metadata_received_at_ns: int,
        *,
        generation: int = ...,
    ) -> BackpackPublicReplay: ...
    def apply_record(
        self, record: bytes
    ) -> (
        model.QuoteTick | model.TradeTick | model.MarkPriceUpdate | model.OrderBookDeltas | None
    ): ...

@typing.final
class BackpackQuota:
    def __new__(
        cls, *, standard_period_ms: int = ..., historical_period_ms: int = ...
    ) -> BackpackQuota: ...
    def shares_scope(self, other: BackpackQuota) -> bool: ...
