# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

from nautilus_trader import model

__all__ = [
    "BACKPACK",
    "BACKPACK_CLIENT_ID",
    "BACKPACK_VENUE",
    "BackpackCredential",
    "BackpackDataClientConfig",
    "BackpackDataClientFactory",
    "BackpackExecutionClientConfig",
    "BackpackExecutionClientFactory",
    "BackpackInstrumentEconomics",
    "BackpackPublicReplay",
    "BackpackQuota",
]

BACKPACK: str
BACKPACK_CLIENT_ID: model.ClientId
BACKPACK_VENUE: model.Venue

@typing.final
class BackpackCredential:
    def __init__(
        self, seed_base64: str, base_url_http: str | None = None, base_url_ws: str | None = None
    ) -> None: ...

@typing.final
class BackpackDataClientConfig:
    @property
    def symbols(self) -> list[str]: ...
    @property
    def economics(self) -> dict[str, BackpackInstrumentEconomics]: ...
    @property
    def base_url_http(self) -> str: ...
    @property
    def base_url_ws(self) -> str: ...
    @property
    def http_timeout_secs(self) -> int: ...
    @property
    def ws_connect_timeout_secs(self) -> int: ...
    @property
    def ws_heartbeat_secs(self) -> int: ...
    @property
    def ws_idle_timeout_secs(self) -> int: ...
    @property
    def reconnect_timeout_secs(self) -> int: ...
    @property
    def shutdown_timeout_secs(self) -> int: ...
    @property
    def quote_stale_after_ms(self) -> int: ...
    @property
    def depth_snapshot_limit(self) -> int: ...
    @property
    def max_buffer_frames(self) -> int: ...
    @property
    def max_levels_per_side(self) -> int: ...
    @property
    def max_ws_message_bytes(self) -> int: ...
    def __new__(
        cls,
        symbols: typing.Sequence[str],
        economics: typing.Mapping[str, BackpackInstrumentEconomics],
        *,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        http_timeout_secs: int | None = None,
        ws_connect_timeout_secs: int | None = None,
        ws_heartbeat_secs: int | None = None,
        ws_idle_timeout_secs: int | None = None,
        reconnect_timeout_secs: int | None = None,
        shutdown_timeout_secs: int | None = None,
        quote_stale_after_ms: int | None = None,
        depth_snapshot_limit: int | None = None,
        max_buffer_frames: int | None = None,
        max_levels_per_side: int | None = None,
        max_ws_message_bytes: int | None = None,
    ) -> BackpackDataClientConfig: ...
    def telemetry_snapshot_json(self) -> str: ...

@typing.final
class BackpackDataClientFactory:
    def __init__(self, quota: BackpackQuota | None = None) -> None: ...
    @property
    def quota(self) -> BackpackQuota: ...
    def name(self) -> str: ...
    @property
    def config_type(self) -> str: ...
    def capabilities_json(self) -> str: ...

@typing.final
class BackpackExecutionClientConfig:
    def __init__(
        self,
        symbols: typing.Sequence[str],
        credential: BackpackCredential,
        account_id: str,
        identity_account: str,
        identity_directory: str,
        quota: BackpackQuota,
        subaccount: str | None = None,
        base_url_http: str | None = None,
        base_url_ws: str | None = None,
        connect_timeout_ms: int = 20000,
        shutdown_timeout_ms: int = 3000,
        recovery_interval_ms: int = 30000,
        recovery_lookback_ms: int = 3600000,
        input_capacity: int = 256,
        fill_capacity: int = 100000,
        page_size: int = 1000,
        max_pages: int = 10,
        max_items: int = 10000,
        read_timeout_ms: int = 30000,
    ) -> None: ...
    @property
    def identity_account(self) -> str: ...
    @property
    def subaccount(self) -> str | None: ...
    @property
    def symbols(self) -> list[str]: ...
    @property
    def account_id(self) -> str: ...
    @property
    def identity_directory(self) -> str: ...
    @property
    def quota(self) -> BackpackQuota: ...
    @property
    def base_url_http(self) -> str: ...
    @property
    def base_url_ws(self) -> str: ...
    @property
    def connect_timeout_ms(self) -> int: ...
    @property
    def shutdown_timeout_ms(self) -> int: ...
    @property
    def recovery_interval_ms(self) -> int: ...
    @property
    def recovery_lookback_ms(self) -> int: ...
    @property
    def input_capacity(self) -> int: ...
    @property
    def fill_capacity(self) -> int: ...
    @property
    def page_size(self) -> int: ...
    @property
    def max_pages(self) -> int: ...
    @property
    def max_items(self) -> int: ...
    @property
    def read_timeout_ms(self) -> int: ...
    def telemetry_snapshot_json(self) -> str: ...

@typing.final
class BackpackExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
    @property
    def config_type(self) -> str: ...
    def capabilities_json(self) -> str: ...

@typing.final
class BackpackInstrumentEconomics:
    @property
    def margin_init(self) -> str: ...
    @property
    def margin_maint(self) -> str: ...
    @property
    def maker_fee(self) -> str: ...
    @property
    def taker_fee(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def source_reference(self) -> str: ...
    def __new__(
        cls,
        margin_init: str,
        margin_maint: str,
        maker_fee: str,
        taker_fee: str,
        source: str,
        source_reference: str,
    ) -> BackpackInstrumentEconomics: ...

@typing.final
class BackpackPublicReplay:
    @property
    def instrument(self) -> model.CryptoPerpetual: ...
    def __new__(
        cls,
        config: BackpackDataClientConfig,
        market_json: str,
        metadata_received_at_ns: int,
        *,
        generation: int = ...,
    ) -> BackpackPublicReplay: ...
    def apply_record(
        self, record: bytes
    ) -> (
        model.QuoteTick | model.TradeTick | model.MarkPriceUpdate | model.OrderBookDeltas | None
    ): ...

@typing.final
class BackpackQuota:
    def __init__(self, standard_period_ms: int = 32, historical_period_ms: int = 2100) -> None: ...
    def shares_scope(self, other: BackpackQuota) -> bool: ...
